import components.simplereader.SimpleReader;
import components.simplereader.SimpleReader1L;
import components.simplewriter.SimpleWriter;
import components.simplewriter.SimpleWriter1L;
import components.xmltree.XMLTree;
import components.xmltree.XMLTree1;

/**
 * Program to convert an XML RSS (version 2.0) feed from a given URL into the
 * corresponding HTML output file.
 *
 * @author Yuting Che
 *
 */
public final class RSSAggregator {

    /**
     * Private constructor so this utility class cannot be instantiated.
     */
    private RSSAggregator() {
    }

    /**
     * Outputs the "opening" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * <html> <head> <title>the channel tag title as the page title</title>
     * </head> <body>
     * <h1>the page title inside a link to the <channel> link</h1>
     * <p>
     * the channel description
     * </p>
     * <table border="1">
     * <tr>
     * <th>Date</th>
     * <th>Source</th>
     * <th>News</th>
     * </tr>
     *
     * @param channel
     *            the channel element XMLTree
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the root of channel is a <channel> tag] and out.is_open
     * @ensures out.content = #out.content * [the HTML "opening" tags]
     */
    private static void outputHeader(XMLTree channel, SimpleWriter out) {
        assert channel != null : "Violation of: channel is not null";
        assert out != null : "Violation of: out is not null";
        assert channel.isTag() && channel.label().equals("channel") : ""
                + "Violation of: the label root of channel is a <channel> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        String headTitle = "";
        String h1Title = "Empty Title";
        String description = "No description";
        if (getChildElement(channel, "title") > -1) {
            if (channel.child(getChildElement(channel, "title"))
                    .numberOfChildren() > 0) {
                h1Title = channel.child(getChildElement(channel, "title"))
                        .child(0).label();
                headTitle = channel.child(getChildElement(channel, "title"))
                        .child(0).label();
            }
        }
        String link = "";
        if (getChildElement(channel, "link") > -1) {
            link = channel.child(getChildElement(channel, "link")).child(0)
                    .label();
        }
        if (getChildElement(channel, "description") > -1) {
            if (channel.child(getChildElement(channel, "description"))
                    .numberOfChildren() > 0) {
                description = channel
                        .child(getChildElement(channel, "description")).child(0)
                        .label();
            }
        }

        out.println("<html> <head> <title>" + headTitle
                + "</title> </head> <body>");
        out.println("<h1> <a href=\"" + link + "\">" + h1Title + "</a> </h1>");
        out.println("<p>" + description + "</p>");
        out.println("<table border=\"1\">");
        out.println("<tr>");
        out.println("<th>Date</th>");
        out.println("<th>Source</th>");
        out.println("<th>News</th>");
        out.println("</tr>");
    }

    /**
     * Outputs the "closing" tags in the generated HTML file. These are the
     * expected elements generated by this method:
     *
     * </table>
     * </body> </html>
     *
     * @param out
     *            the output stream
     * @updates out.contents
     * @requires out.is_open
     * @ensures out.content = #out.content * [the HTML "closing" tags]
     */
    private static void outputFooter(SimpleWriter out) {
        assert out != null : "Violation of: out is not null";
        assert out.isOpen() : "Violation of: out.is_open";

        out.println("</table>");
        out.println("</body> </html>");
    }

    /**
     * Finds the first occurrence of the given tag among the children of the
     * given {@code XMLTree} and return its index; returns -1 if not found.
     *
     * @param xml
     *            the {@code XMLTree} to search
     * @param tag
     *            the tag to look for
     * @return the index of the first child of type tag of the {@code XMLTree}
     *         or -1 if not found
     * @requires [the label of the root of xml is a tag]
     * @ensures <pre>
     * getChildElement =
     *  [the index of the first child of type tag of the {@code XMLTree} or
     *   -1 if not found]
     * </pre>
     */
    private static int getChildElement(XMLTree xml, String tag) {
        assert xml != null : "Violation of: xml is not null";
        assert tag != null : "Violation of: tag is not null";
        assert xml.isTag() : "Violation of: the label root of xml is a tag";

        int index = -1;
        int i = 0;
        while ((index == -1) && (i < xml.numberOfChildren())) {
            if (xml.child(i).label().equals(tag)
                    && (xml.child(i).numberOfChildren() > 0)) {
                index = i;
            }
            i++;
        }
        return index;
    }

    /**
     * Processes one news item and outputs one table row. The row contains three
     * elements: the publication date, the source, and the title (or
     * description) of the item.
     *
     * @param item
     *            the news item
     * @param out
     *            the output stream
     * @updates out.content
     * @requires [the label of the root of item is an <item> tag] and
     *           out.is_open
     * @ensures <pre>
     * out.content = #out.content *
     *   [an HTML table row with publication date, source, and title of news item]
     * </pre>
     */
    private static void processItem(XMLTree item, SimpleWriter out) {
        assert item != null : "Violation of: item is not null";
        assert out != null : "Violation of: out is not null";
        assert item.isTag() && item.label().equals("item") : ""
                + "Violation of: the label root of item is an <item> tag";
        assert out.isOpen() : "Violation of: out.is_open";

        String date = "No date available";
        String sourceLink = "";
        String source = "No source available";
        String news = "No title available";
        String link = "";
        if (getChildElement(item, "pubDate") > -1) {
            date = item.child(getChildElement(item, "pubDate")).child(0)
                    .label();
        }
        if (getChildElement(item, "source") > -1) {
            source = item.child(getChildElement(item, "source")).child(0)
                    .label();
            sourceLink = item.child(getChildElement(item, "source"))
                    .attributeValue("url");
        }
        if (getChildElement(item, "link") > -1) {
            link = item.child(getChildElement(item, "link")).child(0).label();
        }
        if (getChildElement(item, "title") > -1) {
            news = item.child(getChildElement(item, "title")).child(0).label();
        } else {
            if (getChildElement(item, "description") > -1) {
                news = item.child(getChildElement(item, "description")).child(0)
                        .label();
            }
        }
        out.println("<tr>");
        out.println("<th>" + date + "</th>");
        if (sourceLink.equals("")) {
            out.println("<th>" + source + "</th>");
        } else {
            out.println(
                    "<th> <a href=\"" + sourceLink + "\">" + source + "</th>");
        }
        if (link.equals("")) {
            out.println("<th>" + link + news + "</a> </th>");
        } else {
            out.println("<th> <a href=\"" + link + "\">" + news + "</a> </th>");
        }
        out.println("</tr>");

    }

    /**
     * Processes one XML RSS (version 2.0) feed from a given URL converting it
     * into the corresponding HTML output file.
     *
     * @param url
     *            the URL of the RSS feed
     * @param file
     *            the name of the HTML output file
     * @param out
     *            the output stream to report progress or errors
     * @updates out.content
     * @requires out.is_open
     * @ensures <pre>
     * [reads RSS feed from url, saves HTML document with table of news items
     *   to file, appends to out.content any needed messages]
     * </pre>
     */
    private static void processFeed(String url, String file, SimpleWriter out) {
        XMLTree xml = new XMLTree1(url);

        String title = xml.attributeValue("title");
        String h2Title = xml.attributeValue("title");
        String feedUrl = "";
        String name = "";
        String fileName = "";

        out.println("<html>");
        out.println("<head>");
        out.println("<title>" + title + "</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h2>" + h2Title + "</h2>");
        out.println("<ul>");
        for (int i = 0; i < xml.numberOfChildren(); i++) {
            feedUrl = xml.child(i).attributeValue("url");
            name = xml.child(i).attributeValue("name");
            fileName = xml.child(i).attributeValue("file");
            SimpleWriter pageName = new SimpleWriter1L(fileName);

            XMLTree feedXml = new XMLTree1(feedUrl);
            XMLTree channel = feedXml.child(0);
            outputHeader(channel, pageName);
            for (int j = 0; j < channel.numberOfChildren(); j++) {
                if (channel.child(j).label().equals("item")) {
                    processItem(channel.child(j), pageName);
                }
            }
            outputFooter(pageName);
            out.println("<li>" + "<a href=\"" + fileName + "\">" + name
                    + "</a></li>");
            pageName.close();
        }
        out.println("</ul> </body></html>");

    }

    /**
     * Main method.
     *
     * @param args
     *            the command line arguments; unused here
     */
    public static void main(String[] args) {
        SimpleReader in = new SimpleReader1L();
        SimpleWriter out = new SimpleWriter1L();

        out.println("Enter a HTML file name(include: .html):");
        String html = in.nextLine();
        SimpleWriter file = new SimpleWriter1L(html);

        out.println("Enter the URL of an RSS: ");
        String url = in.nextLine();

        processFeed(url, html, file);

        in.close();
        out.close();
        file.close();
    }

}
